import PatternDetector from '../reasoner/PatternDetector.js';
import {perceptionErrorHandler as errorHandler} from '../utils/errorHandler.js';
import {SystemCommands} from './SystemCommands.js';
import {SystemEvents} from './SystemEvents.js';
import {parseTerm} from '../../coreagent/parser/parse-utils.js';

class Perception {
    constructor(memory, taskFactory, eventBus, commandBus) {
        this.memory = memory;
        this.taskFactory = taskFactory;
        this.eventBus = eventBus;
        this.commandBus = commandBus;
        this.patternDetector = new PatternDetector();
        this.sensoryModalities = new Map();
        this.perceptionHistory = [];

        this.commandBus.handle(SystemCommands.PROCESS_RAW_INPUT, (payload) => this._handleProcessRawInput(payload));

        // Register default sensory modalities
        this._registerDefaultModalities();
    }

    _registerDefaultModalities() {
        // Register narsese modality - processes narsese statements into tasks
        this.registerSensoryModality('narsese', async (input) => {
            try {
                // Parse the input as a Narsese statement
                const parsedTerm = parseTerm(input);
                if (!parsedTerm) {
                    console.warn(`Could not parse Narsese input: ${input}`);
                    return [];
                }

                // Extract punctuation from the original input
                let punctuation = '.';
                let trimmedInput = input.trim();

                // Check if the input ends with a punctuation character
                if (trimmedInput.endsWith('!')) {
                    punctuation = '!';
                } else if (trimmedInput.endsWith('?')) {
                    punctuation = '?';
                } else if (trimmedInput.endsWith('.')) {
                    punctuation = '.';
                }

                // Create a task using the private method since there's no public createTask method
                const task = await this.taskFactory._createTask(
                    input, // termKey
                    punctuation, // punctuation
                    null, // truthValue - will be determined by _createTask defaults
                    null // stamp - will be generated by _createTask
                );

                return task ? [task] : [];
            } catch (error) {
                console.error(`Error processing narsese input: ${error.message}`);
                return [];
            }
        });
    }

    registerSensoryModality(modalityName, processor) {
        this.sensoryModalities.set(modalityName, processor);
    }

    async _handleProcessRawInput({modality, input}) {
        const processor = this.sensoryModalities.get(modality);
        if (!processor) {
            throw new Error(`Unknown sensory modality: ${modality}`);
        }

        return await errorHandler.execute(async () => {
            const tasks = await processor(input);
            this.perceptionHistory.push({
                modality,
                input,
                timestamp: Date.now(),
                tasks: tasks.length,
            });

            if (tasks && tasks.length > 0) {
                await this.eventBus.emitAsync(SystemEvents.TASKS_ADD, tasks);
            }

            return tasks;
        }, `_handleProcessRawInput for modality ${modality}`, []);
    }

    async process(events) {
        return await errorHandler.execute(async () => {
            const patternTasks = this.patternDetector.detectPatterns(events);
            const eventTasks = events.map(event => this.taskFactory.convertEventToTask(event));
            return (await Promise.all([...patternTasks, ...eventTasks])).filter(Boolean);
        }, 'process', []);
    }

    getPerceptionHistory() {
        return this.perceptionHistory;
    }

    clearPerceptionHistory() {
        this.perceptionHistory = [];
    }


    getSensoryModalities() {
        return [...this.sensoryModalities.keys()];
    }
}

export default Perception;
