export const PUNCTUATION = {
    BELIEF: '.',
    GOAL: '!',
    QUESTION: '?',
};

export const OP = {
    ATOMIC: 'Atomic',
    INDEPENDENT_VARIABLE: 'IndependentVariable',
    DEPENDENT_VARIABLE: 'DependentVariable',
    QUERY_VARIABLE: 'QueryVariable',
    INHERITANCE: 'Inheritance',
    IMPLICATION: 'Implication',
    EQUIVALENCE: 'Equivalence',
    SIMILARITY: 'Similarity',
    INSTANCE: 'Instance',
    PROPERTY: 'Property',
    PREDICTIVE_IMPLICATION: 'PredictiveImplication',
    RETROSPECTIVE_IMPLICATION: 'RetrospectiveImplication',
    CONCURRENT_IMPLICATION: 'ConcurrentImplication',
    UNTIL: 'Until',
    SINCE: 'Since',
    NEGATION: 'Negation',
    ALWAYS: 'Always',
    EVENTUALLY: 'Eventually',
    NEXT: 'Next',
    PREVIOUS: 'Previous',
    CONJUNCTION: 'Conjunction',
    DISJUNCTION: 'Disjunction',
    SEQUENTIAL_CONJUNCTION: 'SequentialConjunction',
    PARALLEL_CONJUNCTION: 'ParallelConjunction',
    EXTENSIONAL_DIFFERENCE: 'ExtensionalDifference',
    INTENSIONAL_DIFFERENCE: 'IntensionalDifference',
    PRODUCT: 'Product',
    EXTENSIONAL_SET: 'ExtensionalSet',
    INTENSIONAL_SET: 'IntensionalSet',
    NUMBER: 'Number',
    STATEMENT: 'Statement',
};

export const REL = {
    INHERITANCE: '-->',
    IMPLICATION: '==>',
    EQUIVALENCE: '<=>',
    SIMILARITY: '<->',
    INSTANCE: '{--',
    PROPERTY: '--}',
    PREDICTIVE_IMPLICATION: '=\\>',
    RETROSPECTIVE_IMPLICATION: '=/>',
    CONCURRENT_IMPLICATION: '=<>',
    NEGATION: '--,',
    ALWAYS: 'always,',
    EVENTUALLY: 'eventually,',
    NEXT: 'next,',
    PREVIOUS: 'previous,',
    CONJUNCTION: '&,',
    DISJUNCTION: '||,',
    SEQUENTIAL_CONJUNCTION: '&&,',
    PARALLEL_CONJUNCTION: '&|,',
    EXTENSIONAL_DIFFERENCE: '#,',
    INTENSIONAL_DIFFERENCE: '\\\\,',
    PRODUCT: '*,',
};

export const TOKEN = {
    LPAREN: 'lparen',
    RPAREN: 'rparen',
    LBRACE: 'lbrace',
    RBRACE: 'rbrace',
    LBRACKET: 'lbracket',
    RBRACKET: 'rbracket',
    COMMA: 'comma',
    ARROW: 'arrow',
    IMPLIES: 'implies',
    INSTANCE: 'instance',
    PROPERTY: 'property',
    EQUIVALENCE: 'equivalence',
    SIMILARITY: 'similarity',
    RETROSPECTION: 'retrospection',
    PREDICTION: 'prediction',
    CONCURRENT: 'concurrent',
    UNTIL: 'until',
    SINCE: 'since',
    BELIEF: 'belief',
    GOAL: 'goal',
    QUESTION: 'question',
    NEGATION: 'negation',
    ALWAYS: 'always',
    EVENTUALLY: 'eventually',
    NEXT: 'next',
    PREVIOUS: 'previous',
    CONJUNCTION: 'conjunction',
    SEQUENTIAL_CONJUNCTION: 'sequentialConjunction',
    PARALLEL_CONJUNCTION: 'parallelConjunction',
    DISJUNCTION: 'disjunction',
    EXTENSIONAL_DIFFERENCE: 'extensionalDifference',
    INTENSIONAL_DIFFERENCE: 'intensionalDifference',
    PRODUCT: 'product',
    IDENTIFIER: 'identifier',
    STRING: 'string',
    INDEPENDENT_VAR: 'independentVar',
    DEPENDENT_VAR: 'dependentVar',
    QUERY_VAR: 'queryVar',
    NUMBER: 'number',
    WHITESPACE: 'whitespace',
};
