export default {
    REGULARITY_BOOST: 0.7,
    STRUCTURAL_SIMILARITY_WEIGHT: 0.3,
    TEMPORAL_CONFIDENCE: 0.9,
    TEMPORAL_RELATIONSHIP_FREQUENCY: 0.8,
    TEMPORAL_RELATIONSHIP_CONFIDENCE: 0.7,
    MEETS_IMPLICATION_FREQUENCY: 0.9,
    MEETS_IMPLICATION_CONFIDENCE: 0.8,
    OVERLAP_IMPLICATION_FREQUENCY: 0.8,
    OVERLAP_IMPLICATION_CONFIDENCE: 0.7,
    SEQUENCE_CONFIDENCE_DECAY: 0.9,
    PERIODIC_CONFIDENCE: 0.8,
    TEMPORAL_SUMMARY_CONFIDENCE: 0.9,
    PREDICTION_CONFIDENCE: 0.5,
    MAX_COMPARISONS: 1000, // Maximum number of comparisons for temporal reasoning
};