export const CONTRADICTION_TYPES = {
    DIRECT_NEGATION: 'direct_negation',
    INHERITANCE_CONFLICT: 'inheritance_conflict',
    IMPLICATION_CONFLICT: 'implication_conflict',
    TRANSITIVE_INHERITANCE_CONFLICT: 'transitive_inheritance_conflict',
    EQUIVALENCE_CONFLICT: 'equivalence_conflict',
    SET_CONFLICT: 'set_conflict',
    CONJUNCTION_CONFLICT: 'conjunction_conflict',
    DISJUNCTION_CONFLICT: 'disjunction_conflict',
    INTENSIONAL_SET_CONFLICT: 'intensional_set_conflict',
    VARIABLE_CONFLICT: 'variable_conflict',
    TEMPORAL_CONFLICT: 'temporal_conflict',
    GOAL_CONFLICT: 'goal_conflict',
    FREQUENCY_CONFLICT: 'frequency_conflict'
};

// Weights for different contradiction types based on their severity/importance
export const CONTRADICTION_SEVERITY_WEIGHTS = {
    [CONTRADICTION_TYPES.DIRECT_NEGATION]: 1.0,
    [CONTRADICTION_TYPES.INHERITANCE_CONFLICT]: 0.8,
    [CONTRADICTION_TYPES.IMPLICATION_CONFLICT]: 0.8,
    [CONTRADICTION_TYPES.TRANSITIVE_INHERITANCE_CONFLICT]: 0.7,
    [CONTRADICTION_TYPES.EQUIVALENCE_CONFLICT]: 0.7,
    [CONTRADICTION_TYPES.SET_CONFLICT]: 0.7,
    [CONTRADICTION_TYPES.CONJUNCTION_CONFLICT]: 0.65,
    [CONTRADICTION_TYPES.DISJUNCTION_CONFLICT]: 0.65,
    [CONTRADICTION_TYPES.INTENSIONAL_SET_CONFLICT]: 0.65,
    [CONTRADICTION_TYPES.VARIABLE_CONFLICT]: 0.6,
    [CONTRADICTION_TYPES.TEMPORAL_CONFLICT]: 0.6,
    [CONTRADICTION_TYPES.GOAL_CONFLICT]: 0.6,
    [CONTRADICTION_TYPES.FREQUENCY_CONFLICT]: 0.55
};
