/**
 * Interface defining a reasoning strategy in the SeNARS system.
 * All custom reasoning strategies must implement this interface.
 */
export class ReasoningStrategy {
    /**
     * Determines if this strategy can handle the given task in the current context.
     * @param {Task} task - The task to evaluate
     * @param {SystemContext} context - The current system context
     * @returns {boolean} - True if the strategy can handle the task
     */
    canHandle(task, context) {
        throw new Error('Method "canHandle" must be implemented');
    }

    /**
     * Executes the reasoning strategy on the given task.
     * @param {Task} task - The task to process
     * @param {SystemContext} context - The current system context
     * @returns {Promise<TaskResult>} - The result of the reasoning operation
     */
    async execute(task, context) {
        throw new Error('Method "execute" must be implemented');
    }

    /**
     * Gets metadata about this strategy.
     * @returns {StrategyMetadata} - Information about the strategy
     */
    getMetadata() {
        throw new Error('Method "getMetadata" must be implemented');
    }

    /**
     * Validates the input task before execution.
     * @param {Task} task - The task to validate
     * @returns {ValidationResult} - The validation result
     */
    validate(task) {
        // Default implementation - return valid
        return {isValid: true, errors: []};
    }
}

/**
 * Metadata describing a reasoning strategy
 * @typedef {Object} StrategyMetadata
 * @property {string} name - The unique name of the strategy
 * @property {string} description - A brief description of what the strategy does
 * @property {string[]} supportedTaskTypes - Types of tasks this strategy can handle
 * @property {string} category - The category of reasoning (deductive, inductive, etc.)
 * @property {number} priority - Priority level (0-1) when multiple strategies could be used
 */

/**
 * Result of a reasoning operation
 * @typedef {Object} TaskResult
 * @property {Task[]} inferredTasks - Tasks generated by the reasoning operation
 * @property {Object} executionStats - Statistics about the execution
 * @property {boolean} success - Whether the operation was successful
 * @property {string} [errorMessage] - Error message if operation failed
 */

/**
 * Result of a validation operation
 * @typedef {Object} ValidationResult
 * @property {boolean} isValid - Whether the input is valid
 * @property {string[]} errors - List of validation errors
 */